// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check
	// (GET /healthz)
	GetHealthz(c *gin.Context)
	// Get list of clusters
	// (GET /v1/clusters)
	GetV1Clusters(c *gin.Context)
	// Get cluster by ID
	// (GET /v1/clusters/{id})
	GetV1ClustersId(c *gin.Context, id string)
	// Get nodes of a cluster by cluster ID
	// (GET /v1/clusters/{id}/nodes)
	GetV1ClustersIdNodes(c *gin.Context, id string)
	// Get local cluster info
	// (GET /v1/info)
	GetV1Info(c *gin.Context)
	// Get list of namespaces
	// (GET /v1/namespaces)
	GetV1Namespaces(c *gin.Context)
	// Get namespace by name
	// (GET /v1/namespaces/{name})
	GetV1NamespacesName(c *gin.Context, name string)
	// Get offloaded pods by namespace name
	// (GET /v1/namespaces/{name}/offloaded)
	GetV1NamespacesNameOffloaded(c *gin.Context, name string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealthz(c)
}

// GetV1Clusters operation middleware
func (siw *ServerInterfaceWrapper) GetV1Clusters(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Clusters(c)
}

// GetV1ClustersId operation middleware
func (siw *ServerInterfaceWrapper) GetV1ClustersId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1ClustersId(c, id)
}

// GetV1ClustersIdNodes operation middleware
func (siw *ServerInterfaceWrapper) GetV1ClustersIdNodes(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1ClustersIdNodes(c, id)
}

// GetV1Info operation middleware
func (siw *ServerInterfaceWrapper) GetV1Info(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Info(c)
}

// GetV1Namespaces operation middleware
func (siw *ServerInterfaceWrapper) GetV1Namespaces(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1Namespaces(c)
}

// GetV1NamespacesName operation middleware
func (siw *ServerInterfaceWrapper) GetV1NamespacesName(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1NamespacesName(c, name)
}

// GetV1NamespacesNameOffloaded operation middleware
func (siw *ServerInterfaceWrapper) GetV1NamespacesNameOffloaded(c *gin.Context) {

	var err error

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetV1NamespacesNameOffloaded(c, name)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz)
	router.GET(options.BaseURL+"/v1/clusters", wrapper.GetV1Clusters)
	router.GET(options.BaseURL+"/v1/clusters/:id", wrapper.GetV1ClustersId)
	router.GET(options.BaseURL+"/v1/clusters/:id/nodes", wrapper.GetV1ClustersIdNodes)
	router.GET(options.BaseURL+"/v1/info", wrapper.GetV1Info)
	router.GET(options.BaseURL+"/v1/namespaces", wrapper.GetV1Namespaces)
	router.GET(options.BaseURL+"/v1/namespaces/:name", wrapper.GetV1NamespacesName)
	router.GET(options.BaseURL+"/v1/namespaces/:name/offloaded", wrapper.GetV1NamespacesNameOffloaded)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYS4/bNhD+Kwbbo7K2NwVa+Gbs5mE0tY110kODHGhxbDOhOApJOesu/N8LUtTLomx5",
	"ixQpsMBSmhmS8803D/mJxJikKEEaTSZPRMc7SKhb3olMG1AzuUH7mCpMQRkOTrgDKszOrn5WsCET8tOw",
	"2mjodxm+dVpuh2NEBMZUXDJ5Z5XqRx8jIsF8Q/Xlkuk8VyusUgDF5VZfMlt6vdzuGBFzSIFMCK4/Q2zs",
	"TncoGTcc5cpQk7kNQWYJmXwkc5RAIrIEybjckoi80oauBdc7YPZJKVQkIg9A2YFEZI6mWK4wgfLxU3mq",
	"NvYy9tTXqIBvpceiHQKa8hWoPajqVufcPHXiGFU7fFAuLq0r0MzsQBoe06b3V57DWXB3H9Z31ICMD+dU",
	"nn0ybjYCqQ3Ns7dQoDFTMehp/DXjCtilPR4Kg4b1YrOBq41RQJ1sdyh1loAl1FLhnjO3LN5OJau9/SC/",
	"SPwmA8wKMbyWqB2pXo/PGlEAldYwk168RJazkuUAUrFs7HI2A5HlFyDtu4Vu26oRrTtPl7Oc2VPGVJBZ",
	"sTe/D0oFXYM460/LpHXLPSjNUQaUQ9pzmoBOaQxtZ2IFLv/e8ySnwyNNUssMcju6Hb8Y/fpiNH4/Gk3c",
	"318kUEokzS1bgio/LsVoUWkeI6JbhXAaG763pfA9qIRLaqxmP/LV63bLeXg0oCQVd7P7h6ALXF5QSJF1",
	"yjSoPY+hQx68LLJQiGhKY24OV6V3YfRBX1kXznO3I9ghZxaN8DddkgUh/6Bp6gqooga2h3rQX8kNqhhW",
	"NAHLXxKRe9jQTBj/tAIBsQHmHkM9ruLfckd1o9hVLdNnerEZichMLhVuFWjtG+lryoWTTIUo1+eZ6Iix",
	"qPWHtnuuzrjunaCx/rgXU8n8i370tvNFmNtd7fXKYuWbZKPJnUH6jFLRcHp6VU5NLc/s7OUW3EDSawIr",
	"pjZ/EFWKHjpORvY9aiRP6LYoOd72IwG5x0Oq8PEwdMsXVKRcwmQ/vhn/dvOSRERuuXycjG/Gv9zcWkKU",
	"Dnc1CO/Zs3pMeTM7/aVkkp8e7D6dJV/WG01biixP5SA9QBuqzBIFjxuJMhXf6MHm4kLa7MuUTZY57EEF",
	"E6/dPar5+SGTMl+tsjgGYC6Vy5y+bqypBosWYZQtL3coDeXSc9Wb24ayBVVzuEOquxPJoKHi/O6h+1ZV",
	"vk3wNGvyehwiMaQ7SEBRsTKo6PYkFcajNzxklUCC6tBPN/VzXk1zPCI9onF0vTovFoYbZ/qOf8WBwRQF",
	"bg8DRvVujVTZOJfDExnfjG5GroKlIGnKyYS8dK8iklKzc5cZ5kPo33a9BWP/WexcRZgxMiFvwLz1Ki6q",
	"KUqd43o7Gtl/DHSseGryMxe/Ow90liTUAuPn40G8g/iLEw3346GvyvrcqX+O7wqt8MExSgPS+JQWvhcM",
	"P+t8csxLZO9KevLN2K6nx+jE1elAcG0GuBmU7jRdfwMmrFKHYPjE2bEfDjPmIqdoAjl4H58Itzex0SRF",
	"4bLfjBaw4pPLqAyiGhqndPv0L9G9BtQQiHEpPMXOSwbrw2B2HwZuaKuu7gvf3Cn/zzB0Y3MQOZlLTmFz",
	"kFjO0TqCxbKGZFFTuqFzo8V39K3xa1XbRTc0ljfnxa9MJxkWVrIOlg37AkPmld5/UWqqD9arqkzNm+46",
	"c6LURGH4ZNfHvmD4T5HL2SJzxR8kXyp0g0lTE7cyp5DZhHFOdWI49F8F+fdnXzQXpdEPCWu/Tw5k1/G2",
	"RGrgJqA27E2FAvs8ED4Kx+M/AQAA//+JInYvbxcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
